### ISSUE TITLE
oi

### ISSUE THREAD

**Issue by MiiKoga** [AugustoPinheiro/AugustoPinheiro#1]
single?

**Comment by AugustoPinheiro** [comment]
![c1f2c85f4e6e174b4fe2fb655ec28dfe](https://user-images.githubusercontent.com/33337164/124693092-70004200-dea4-11eb-81ec-f8942edc5fc8.gif)

**Comment by AugustoPinheiro** [comment]
![Uploading fc570dfc196aedc553a8519590ac1a7abd2bd230_hq.gif…]()

**Comment by AugustoPinheiro** [comment]
![fc570dfc196aedc553a8519590ac1a7abd2bd230_hq](https://user-images.githubusercontent.com/33337164/124769249-edf13700-defe-11eb-8dfa-2676d97a9029.gif)
